### ISSUE TITLE
how to cite

### ISSUE THREAD

**Issue by arademaker** [delph-in/docs#11]
1. LKB and LKB FOS?
2. Ace
3. Pet

**Comment by olzama** [comment]
1. https://github.com/delph-in/docs/wiki/LkbCopyright (actually found in https://github.com/delph-in/docs/wiki/LkbCopyright !)
2. I believe the canonical citation is Crysmann, Berthold, and Woodley Packard. "Towards efficient HPSG generation for German, a non-configurational language." Proceedings of COLING 2012. 2012 but I think adding also the URL (http://sweaglesw.org/linguistics/ace/) is appropriate here. 
3. http://www.coli.uni-saarland.de/~uc/thesis/thesis.pdf (also found via https://github.com/delph-in/docs/wiki/PetTop :) )

**Comment by arademaker** [comment]
For Ace I added in https://github.com/delph-in/docs/wiki/AceFaq the bibtex entry.

**Comment by arademaker** [comment]
For Pet, I also add one explicit section about it in the end of https://github.com/delph-in/docs/wiki/PetTop. External links are not stable, I think it would be nice to try a better and uniform approach to citations in the wiki.

**Comment by arademaker** [comment]
For Lkb, not sure if the license is the best page to cite. What about the @anncopestake book http://web.stanford.edu/group/cslipublications/cslipublications/site/1575862603.shtml?

**Comment by olzama** [comment]
> For Lkb, not sure if the license is the best page to cite. What about the @anncopestake book http://web.stanford.edu/group/cslipublications/cslipublications/site/1575862603.shtml?

Oh, you are right of course. I misread it; I thought that was the book.

**Comment by olzama** [comment]
Is this resolved now?

**Comment by arademaker** [comment]
Yes. The broader suggestion would be a long term goal.. explicit info about "how to cite" in all relevant pages.

**Comment by arademaker** [comment]
Hum, it looks like people already have the ideia that I have in mind before, see https://github.com/delph-in/docs/wiki/LtgOslo_BibTeX.
