### ISSUE TITLE
AceFaq

### ISSUE THREAD

**Issue by arademaker** [delph-in/docs#13]
https://github.com/delph-in/docs/wiki/AceFaq#what-does-lexemes-do-not-span-position---message-means-when-ace-is-run-to-parse-sentences

In this question, it was not clear what parts should be put inside a code block... can someone help?

**Comment by olzama** [comment]
In the original wiki, there are no code blocks in that section. Or did you seek to improve it?

**Comment by arademaker** [comment]
Yes, I want to improve it. I added the clear cases. But this section I mentioned is not clear to me.

**Comment by olzama** [comment]
OK, I think most of what I now put in a code block is actually output (though I am not sure about `<!-- -->`)

**Comment by arademaker** [comment]
OK, I believe the page is better now and we can close this issue. I removed the scape of the vertical bars from the verbatim blocks, they are not necessary.
