### ISSUE TITLE
MoinMoin usernames and GitHub usernames

### ISSUE THREAD

**Issue by guyemerson** [delph-in/docs#16]
The old personal homepages have [been removed](https://github.com/delph-in/docs/issues/1), but we agreed it could be useful to map the old MoinMoin usernames to current GitHub usernames.  We have a list of usernames on the [ParticipantsGroup page](https://github.com/delph-in/docs/wiki/ParticipantsGroup), and perhaps we could start adding GitHub usernames there.

**Comment by guyemerson** [comment]
I've done an initial pass.

**Comment by arademaker** [comment]
Yep, good idea. Note that the migration script was able to preserve the author of the pages in MoinMoin. For example, see in https://github.com/delph-in/docs/wiki/AceCsaw that the last author is WoodleyPackard, and the history also mentions the correct usernames https://github.com/delph-in/docs/wiki/AceCsaw/_history.

**Comment by arademaker** [comment]
For new users, what should we do? I added as a normal name (no WikiName) with a link to the GitHub page.

**Comment by guyemerson** [comment]
I don't know if we need to keep this page long-term and update it with new users.  On MoinMoin it had another use, but it seems like a legacy page now.  I used it just because it seemed like a reasonable starting point.

**Comment by arademaker** [comment]
I will close this issue. The page started by @guyemerson can be improved by demand, whenever we find a new GitHub userid  now linked there.
