### ISSUE TITLE
Intra-wiki links are broken or not updated

### ISSUE THREAD

**Issue by goodmami** [delph-in/docs#2]
It seems that links between wiki pages, except for from the main wiki page, are broken. For instance, go to https://github.com/delph-in/docs/wiki/LogonTop and try to click on a wiki link, like `LogonPet`. It links to

    https://github.com/delph-in/docs/LogonPet

instead of

    https://github.com/delph-in/docs/wiki/LogonPet

Similarly, some wiki links were apparently specified as absolute URLs originally, so they didn't get converted to the GitHub URLs. For instance, at https://github.com/delph-in/docs/wiki/MatrixTop, the link to the KRG is

    http://wiki.delph-in.net/moin/KrgTop

**Comment by arademaker** [comment]
Yes, I know. The migration was not finished. Actually, I may need to recreate the wiki from scratch tomorrow.

**Comment by goodmami** [comment]
Ok, sounds good.

Also I just noticed that the absolute URLs may be unconverted because they are wrong:

    http://wiki.delph-in.net/moin/KrgTop

should be

    http://moin.delph-in.net/wiki/KrgTop

So maybe in your conversion script you can also look for `wiki.delph-in.net/moin/` and pretend it were `moin.delph-in.net/wiki/`?

**Comment by arademaker** [comment]
Thanks. I will try my best to fix the links, but we may need some manual work...

**Comment by arademaker** [comment]
the list of pages with absolute links not converted are:

```
% grep -R -c "http://wiki.delph-in.net/" * | awk -F ":" '$2 > 0'
DelphinNews.md:1
DelphinStudents.md:2
DocumentationParty.md:1
FeforPlenum.md:1
GrammarCatalogue.md:6
HeartofgoldTop.md:1
JacyTop.md:1
LisbonEvaluationDiscussion.md:1
LkbLtdb.md:1
LkbLui.md:1
MatrixTop.md:1
NoraExtraction.md:1
UnificationApi.md:1
Updating_the_Customization_System.md:1
```

We will need to fix them manually.

**Comment by olzama** [comment]
I fixed the ones associated with the old wiki. There may be more broken links of other types, of course!
