### ISSUE TITLE
docs repository 

### ISSUE THREAD

**Issue by arademaker** [delph-in/docs#26]
Hi @guyemerson , the file https://github.com/delph-in/docs/blob/main/Conrad_DELPH-IN_thesis_presentation.pdf in the root folder is not a good practice. Should we create a folder for a specific purpose? Is it related to the last summit?

**Comment by goodmami** [comment]
@arademaker it looks like Liz, not Guy, uploaded the file. She uploaded twice, once in the root directory and another time under `summits/2021/`. Only the latter is linked by the wiki. I think we can just remove the one in the root directory.

**Comment by guyemerson** [comment]
I've removed the duplicate file.

**Comment by arademaker** [comment]
Sorry @guyemerso, my mistake
