### ISSUE TITLE
Redwoods splits documentation

### ISSUE THREAD

**Issue by olzama** [delph-in/docs#36]
I note that in the latest version of redwoods.xls (released with the 2020 version of the ERG) the 2020 tab is missing and the most recent tab is 2018. @danflick is there in fact a 2020 tab that you forgot to include or was it not part of the release? (Or maybe the release is for now only semi-official?)

**Comment by olzama** [comment]
Also, the colorcoding I think broke in the wiki: https://github.com/delph-in/docs/wiki/RedwoodsTop#standard-splits -- and I don't know what it was, so someone else should fix it

**Comment by goodmami** [comment]
The colors are here: http://moin.delph-in.net/wiki/RedwoodsTop

We probably need to make an image since I think GitHub sanitizes the HTML attributes needed to recreate the colors.

**Comment by olzama** [comment]
Thanks, @danflick ! And what about the 2020 tab in redwoods.xls, does it exist or not yet?

**Comment by danflick** [comment]
I have just now added the 2020 tab in redwoods.xls in the svn repository for the 2020 ERG, so you'll pick it up if you do svn update. (You'll also see that I corrected some flawed files in the "fracas" gold profile.) Thanks for the reminder.

**Comment by olzama** [comment]
Thank you so much, @danflick !

**Comment by olzama** [comment]
@danflick I noticed that the coverage in 2020 is lower compared to 2018, looks like across the board. Is this expected, do you know roughly what it is related to, which type of changes?
