### ISSUE TITLE
Running lkb_fos

### ISSUE THREAD

**Issue by RuiPChaves** [delph-in/docs#38]
Hello,
Is it possible to run LKB-FOS from a Linux bash terminal, without Emacs?
Thank you!
Rui

**Comment by leoalenc** [comment]
> Hello, Is it possible to run LKB-FOS from a Linux bash terminal, without Emacs? Thank you! Rui

Hi, @RuiPChaves , this is possible. Just run 

`~/delphin/lkb_fos$ ./lkb.linux_x86_64`
 

> Welcome to LKB 5.5 (built with SBCL, 05:45:08 18 Jul 2021)
> 
> * 

This command opens the Lkb Top GUI window.

**Comment by olzama** [comment]
Hi Rui,

Let us know if this worked! 

As a suggestion, for Q&A, consider using the Q&A forum: https://delphinqa.ling.washington.edu/ -- it is then easier for others to find solutions which were already posted.

**Comment by olzama** [comment]
In principle, this info can be found here: https://github.com/delph-in/docs/wiki/LkbFos -- but should we make it more visible, like create a subheading "Running LKB FOS from the terminal"?

**Comment by RuiPChaves** [comment]
Hi Olga, I thought the git page was the right place to post in! My apologies. I will use the Q&A forum instead in the future.
Thanks!

**Comment by arademaker** [comment]
Most important is if you have the answers that you were looking for. Let us know. I will close this issue for now.
