### ISSUE TITLE
Flickinger 2011 pdf and/or link

### ISSUE THREAD

**Issue by olzama** [delph-in/docs#39]
This link seems dead: http://lists.delph-in.net/archives/developers/attachments/20180514/ffe9ae3d/attachment-0001.pdf

It is supposed to be the link to @danflick 's 2011 paper "Accuracy v. robustness in grammar engineering".

I'd like to recover the paper both to fix some of our wiki pages and also to learn more about the treebanks. (I am finding the descriptions in https://github.com/delph-in/docs/wiki/RedwoodsTop not sufficient for someone who hasn't worked with the datasets before e.g. I know what WSJ or wikipedia is but have no idea about some of the other datasets there. But that's a separate issue; I will open a new one if the 2011 paper is not enough).

**Comment by danflick** [comment]
Yes, please open a separate issue for updating the RedwoodsTop page. I'll work with my co-curator to bring it up to date for the 2020 version of the ERG and its treebanked profiles.  I will add descriptions of the component profiles.  In the meantime, you can find brief but possibly helpful descriptions of these profiles in the file erg/tsdb/skeletons/Index.lisp.
As for the issue of broken links to archived DELPH-IN-related papers, it looks like we'll have to work out a strategy for where to store them.  For now, I'm attaching the 2011 paper you needed.
[flickinger2011.pdf](https://github.com/delph-in/docs/files/7828009/flickinger2011.pdf)

**Comment by olzama** [comment]
thanks, Dan! There is already a couple issues for RedwoodsTop: https://github.com/delph-in/docs/issues/35 and https://github.com/delph-in/docs/issues/40
