### ISSUE TITLE
Wiki subheader shortcuts are broken

### ISSUE THREAD

**Issue by olzama** [delph-in/docs#5]
E.g. in https://github.com/delph-in/docs/wiki/MatrixRegressionTesting :

There are shortcuts to "Create" a test or "Run" a test, which in moinmoin would link to a subheader on the current page. Right now they lead to a 404 error: https://github.com/MatrixRegressionTesting#create

Same if the shortcut is to a subheader on another page: https://github.com/MatrixDevTop#repository

**Comment by arademaker** [comment]
In this situation, better use a named anchor for the target and use it to create the link. I have done it. See  https://github.com/delph-in/docs/wiki/MatrixRegressionTesting and https://github.com/delph-in/docs/wiki/MatrixDevTop
